import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Scanner;

public class RockPaperSci {
    public final static List<String> OPTIONS = Arrays.asList("rock", "paper", "scissor");

    // Rules defines Keys and Values where key beats values
    public final static Map<String, String> RULES = new HashMap<>();

    static {
        RULES.put("rock", "scissor");     // rock beats scissors
        RULES.put("paper", "rock");        // paper beats rock
        RULES.put("scissors", "paper");   // scissors beats paper
    }

    public static void main(String[] args) {
        Random random = new Random();
        Scanner sc = new Scanner(System.in);
        boolean playAgain = true;
        while (playAgain) {
            System.out.println("Enter your choice (Rock, Paper, Scissor)");
            String userInput = sc.next().toLowerCase();

            // check if choice of user is not valid
            if (!OPTIONS.contains(userInput)) {
                System.out.println("Invalid Choice. Please enter the correct choice");
                continue;
            }

            //Random input generated by computer
            System.out.println("Option selected by Computer");
            String computerInput = OPTIONS.get(random.nextInt(OPTIONS.size()));
            System.out.println(computerInput.toUpperCase());

            System.out.println(play(userInput, computerInput));

            // Ask if user wants to play again
            System.out.println("Play Again? (yes/no)");
            playAgain = sc.next().equalsIgnoreCase("yes");

        }
    }

    /**
     *
     * @param userInput - choice entered by user
     * @param computerInput - choice entered by computer
     * @return result string
     */
    public static String play(String userInput, String computerInput) {
        if (userInput.equals(computerInput)) {
            return "Options selected by user and computer are same. Its a draw match";
        } else if (RULES.get(userInput).equals(computerInput)) {
            return "You Win!!";
        } else {
            return "Computer Wins!!";
        }
    }
}
